apiVersion: v1
kind: Service
metadata:
  name: finvista-service
  labels:
    app: finvista-rag
spec:
  type: LoadBalancer
  selector:
    app: finvista-rag
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501